#!/usr/bin/env bash
# Displays FizzBuzz when the number is a multiple of 3 and 5 Displays Fizz
i=0
while [ $i -lt 100 ]
do
    ((i++))

  if [ $(( i % 3 )) == 0 ] && [  $(( i % 5 )) == 0 ]; then
      echo "FizzBuzz"
  elif [ $(( i % 3 )) == 0 ]; then
      echo "Fizz"
  elif [ $(( i % 5 )) == 0 ]; then
      echo "Buzz"
  else
      echo $i
  fi
done
